### ISSUE TITLE
Call wp_die in `wp_cache_init`

### ISSUE THREAD

**Issue by spacedmonkey** [OllieJones/sqlite-object-cache#15]
Instead of calling `throw new \RuntimeException` and letting the fatel error handle show a message, call `wp_die` directly. 

Like this 
```
	function wp_cache_init() {
		$message = WP_Object_Cache::has_sqlite();
		if ( true === $message ) {
			// We need to override this WordPress global in order to inject our cache.
			// phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
			$GLOBALS['wp_object_cache'] = new WP_Object_Cache();
		} else {
			wp_die( $message );
		}
	}
```

![Screenshot from 2023-01-27 11-56-13](https://user-images.githubusercontent.com/237508/215080783-0053316d-9f6e-4745-9379-498576c0de48.png)

**Comment by OllieJones** [comment]
Great, thanks for the suggestion!
