### ISSUE TITLE
Implement `WP_CACHE_KEY_SALT` const

### ISSUE THREAD

**Issue by spacedmonkey** [OllieJones/sqlite-object-cache#16]
The `WP_CACHE_KEY_SALT` const is used to cache invalidate. Core uses and many popular plugins use it as well. This plugin should use it as well.

**Comment by OllieJones** [comment]
Each site (or network containing multiple sites) creates its own cache .sqlite file. The primary purpose of this "salt" is to tag entries from different sites/networks that share a single cache. Agreed that it should be there to meet user expectations, but it is, strictly speaking, not necessary.

If a future version of this allows the sharing of .sqlite files by multiple sites/networks, this will become useful.

**Comment by spacedmonkey** [comment]
There are a couple of ways to implement this. 

1. Add the salt to the key generation. [See](https://github.com/WordPress/wordpress-develop/blob/bce2a0a534f09a66fde20512b87c3a3c107225d5/tests/phpunit/includes/object-cache.php#L2132-L2144) 
2. Prefix the file name with salt. 

`WP_CACHE_KEY_SALT` is used by all of the popular object caching drop-ins. [Even](https://github.com/pantheon-systems/wp-redis/blob/b0ba3867f6ddd170359773ed661a2cd81fdc6122/object-cache.php#L8-L10) wp-redis, which this plugin is based on.

**Comment by OllieJones** [comment]
We append the salt to the cache's SQLite filename. (There's nothing to be gained by lengthening the cache item names, because each .sqlite file is used for only one install anyway.
