### ISSUE TITLE
Stats do not seem to working

### ISSUE THREAD

**Issue by spacedmonkey** [OllieJones/sqlite-object-cache#17]
Even through had use the plugin for a couple of hours, there seems to be no stats at all. 

![Screenshot from 2023-01-27 12-11-41](https://user-images.githubusercontent.com/237508/215084303-6e0f0f55-22c0-4cf3-bc6c-b241c2ad8d50.png)

**Comment by OllieJones** [comment]
Performance measurements must be enabled in the Settings tab. Added a note to that effect.

**Comment by spacedmonkey** [comment]
They were enabled.

**Comment by OllieJones** [comment]
The default sample rate is a 1% random sample (using [lcg_rand](https://www.php.net/manual/en/function.lcg-value.php)) of page requests. I suspect you chose that rate and then didn't get lucky.  At any rate now you get an explanation for absent stats.
