### ISSUE TITLE
Change theming seeing this error. 

### ISSUE THREAD

**Issue by spacedmonkey** [OllieJones/sqlite-object-cache#19]
When I changed theme, I saw the following error. 

![Screenshot from 2023-01-27 12-24-06](https://user-images.githubusercontent.com/237508/215086409-f5f093fa-dfee-425d-ad0d-5ce4614f39d4.png)

**Comment by OllieJones** [comment]
Tracking this down.  .sqlite file corruption should be concealed to the extent possible. 

Theme changes didn't cause this for me.  Maybe use the force-corruption script to generate this.

`sudo dd bs=1024 skip=10 count=100 if=/dev/urandom of=.ht.object-cache.sql`

**Comment by OllieJones** [comment]
I cannot reproduce this problem after I straightened out the exception handling.
