### ISSUE TITLE
Option to change default DB file name

### ISSUE THREAD

**Issue by nawawi** [OllieJones/sqlite-object-cache#7]
Hi there,

Thanks for your great work.

Currently, by default, we can download the DB file (siteurl/wp-content/object-cache.sqlite) which can lead to security issues.  For example, from the downloaded DB file we can extract user info:
```
select * from object_cache where name like '%user%';
```
![image](https://user-images.githubusercontent.com/1203635/206531684-7c0cc969-f8ce-43ce-8630-0207850890ce.png)

My suggestions:
1. Rename it with the prefix ".ht" which by default most web server configurations prevent access to the file. For example ".ht.object-cache.sqlite"
2. Have the option to change the DB file name and location.

Thanks.

**Comment by OllieJones** [comment]
Good catch, thank you.

**Comment by OllieJones** [comment]
Thanks for this bug report, it's fixed in v 1.0.0.

**Comment by nawawi** [comment]
Thanks!
